services:
  ollama:
    build: 
      dockerfile: Dockerfile.ollama
      context: .
      args:
          # This maps the variable from your .env file to the Docker build
          - OLLAMA_SMALL_MODEL=${OLLAMA_SMALL_MODEL}
          - OLLAMA_MEDIUM_MODEL=${OLLAMA_MEDIUM_MODEL}
    container_name: ollama
    volumes:
      - ./ollama_data:/root/.ollama
    # Comment this deploy stanza out if you don't have an nvidia gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - OLLAMA_NO_CLOUD:true
      - OLLAMA_SMALL_MODEL=${OLLAMA_SMALL_MODEL}
      - OLLAMA_MEDIUM_MODEL=${OLLAMA_MEDIUM_MODEL}
    network_mode: host    

  open-webui:
    build: 
      dockerfile: Dockerfile.open_webui
      context: .
    container_name: open-webui
    ports:
      - "127.0.0.1:4000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - DEFAULT_MODELS=${OLLAMA_SMALL_MODEL}
      - WEBUI_AUTH=false
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./open_webui_data:/app/backend/data
    depends_on:
      - ollama
    restart: always

volumes:
  ollama:
  open-webui: